name: Deploy

on:
  push:
    branches: [prod] #branch names

concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.ref_name }}
            ${{ env.IMAGE }}:${{ github.sha }}
      
      - name: Generate .env for container
        run: |
          cat > deploy.env <<EOF
          IMAGE=${{ env.IMAGE }}
          IMAGE_TAG=${{ github.sha }}
          PORT=${{ vars.PORT }}
          MEM_LIMIT_MB=${{ vars.MEM_LIMIT_MB }}
          CPU_LIMIT_CORES=${{ vars.CPU_LIMIT_CORES }}
          EOF
      
      - name: Ensure app directory exists on VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST_VM }}
          username: deploy
          key: ${{ secrets.HOST_VM_SSH }}
          script: mkdir -p /srv/apps/${{ vars.APP_NAME }}
 
      - name: Ship compose file and .env to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.HOST_VM }}
          username: deploy
          key: ${{ secrets.HOST_VM_SSH }}
          source: "compose.yaml,deploy.env"
          target: /srv/apps/${{ vars.APP_NAME }}/
 
      - name: Pull and start
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST_VM }}
          username: deploy
          key: ${{ secrets.HOST_VM_SSH }}
          script: |
            cd /srv/apps/${{ vars.APP_NAME }}
            mv deploy.env .env
            echo "${{ secrets.GHCR_PULL_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull
            docker compose up -d
            docker image prune -f